### ISSUE TITLE
请问可否提供一份新版本在ar71xx编译后的ipk文件？

### ISSUE THREAD

**Issue by GregoryZeng** [zonyitoo/sysuh3c#10]
自从昨天有人更新源代码后，我尝试安装OpenWrt SDK，但无奈搭建环境过程中遇到了很多麻烦。所以请问是否有好心人提供ar71xx的ipk呢？非常感谢。

**Comment by zonyitoo** [comment]
This is not an issue. Welcome to push a PR for this.

**Comment by homeqian** [comment]
同上 也在搭建环境过程中出现了很多麻烦。求一份ar71xx的ipk
