### ISSUE TITLE
新版本ar71xx的ipk在openwrt上md5验证失败

### ISSUE THREAD

**Issue by OneMoreSec** [zonyitoo/sysuh3c#16]
openwrt上登陆的错误信息
`EAP Auth Start`
`Got EAP Request for Identity`
`Got EAP Request for MD5-Challenge`
`EAP Failure`

**Comment by zonyitoo** [comment]
尝试加参数 `-m md5`, ref: #13

**Comment by Qznan** [comment]
实测至八加参数-m md5成功

**Comment by zenghsh3** [comment]
遇到同样问题也，加了md5参数也不行也==至八

**Comment by zonyitoo** [comment]
如果不行的话，先确认下密码及帐号有没有过期？

**Comment by zonyitoo** [comment]
Close because of inactively.
