### ISSUE TITLE
总是Socket recv error

### ISSUE THREAD

**Issue by jzeng9** [zonyitoo/sysuh3c#17]
初用Ubuntu，想问一下Socket recv error是什么方面的问题。
![image](https://cloud.githubusercontent.com/assets/13816296/20188635/838825a8-a7b4-11e6-9d92-fb8a7136cc61.png)

**Comment by kamingchan** [comment]
加个 sudo 试试

**Comment by jzeng9** [comment]
果断加过了，不加运行不了 @bazingaterry

**Comment by kamingchan** [comment]
@sysustrange `sudo ifconfig` 看看网卡名字有没有错

**Comment by jzeng9** [comment]
没的，eth0是和默认的是一个名字 @bazingaterry

**Comment by zonyitoo** [comment]
Close because of inactively.
