### ISSUE TITLE
Does it support pi?

### ISSUE THREAD

**Issue by Wsine** [zonyitoo/sysuh3c#18]
\# sysuh3c --user xxx
Argument Error. Unknown option.

\# sysuh3c -h is ok.

**Comment by zonyitoo** [comment]
I don't think pi (Linux) has anything special compares to other platforms.

Have you tried `sysuh3c -u xxx`?

**Comment by Wsine** [comment]
The reason is function getopt_long does not support arm.
It will always catch default tag.
I trid to modify the code and have fixed it.
It works. Thank you!
