### ISSUE TITLE
使用时出现segmentation fault

### ISSUE THREAD

**Issue by songfeil** [zonyitoo/sysuh3c#19]
路由器为小米mini，PandoraBox 17.01 2017-01-03-git-6c24a7a
使用eth0.2接口拨号时出现如下提示
[root@PandoraBox_5EF5:/root]#sysuh3c -u wangmy2
Password: EAP Auth Start
Segmentation fault

**Comment by zonyitoo** [comment]
提供gdb或其它可debug信息

**Comment by zonyitoo** [comment]
Close because of inactive.
