### ISSUE TITLE
openwrt 版本需要考虑是否放出

### ISSUE THREAD

**Issue by humiaozuzu** [zonyitoo/sysuh3c#2]
因为违反了网络中心的相关规定，可能会去喝茶。

**Comment by zonyitoo** [comment]
(°Д°≡°д°)ｴｯ!? 那Linux下的自定义客户端不也违反了嘛，不怕啦……

**Comment by humiaozuzu** [comment]
不要放出交叉编译到 openwrt 的教程就安全。

**Comment by zonyitoo** [comment]
我投降了，那就不要放出来了，让其他人自己搜索吧

**Comment by sser-huangdong** [comment]
突然重置路由，发现clih3c的项目不见了，好彩旧电脑有备份，师兄都毕业了，不怕喝茶了吧

**Comment by zonyitoo** [comment]
@sser-huangdong 改名成sysuh3c了，一样的代码

**Comment by sser-huangdong** [comment]
可是没有ipk文件好麻烦

**Comment by zonyitoo** [comment]
@sser-huangdong 有啊，https://github.com/zonyitoo/sysuh3c/tree/openwrt

**Comment by sser-huangdong** [comment]
get  好像之前也是要换branch

**Comment by chengkun-wu** [comment]
我的极路由2(CPU是mt7620a)刷了openwrt以后，我试着安装rampis那个架构的ipk, 报如下错误：

opkg install sysuh3c_0.2-1_2016_ramips.ipk

Collected errors:
 * deb_extract: sysuh3c_0.2-1_2016_ramips.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from sysuh3c_0.2-1_2016_ramips.ipk.

请问怎么解决？谢谢！
