### ISSUE TITLE
OPENWRT,AR71XX

### ISSUE THREAD

**Issue by LMX58** [zonyitoo/sysuh3c#26]
在AR71XX架构的OPENWRT路由器安装时出现错误，请问应该如何处理。

**Comment by zonyitoo** [comment]
1. 什么错误
2. 怎么安装

**Comment by LMX58** [comment]
pkg_hash_fetch_best_installation_candidate: Packages for sysuh3c found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package sysuh3c.

上传到TMP目录，然后opkg install进行安装

**Comment by zonyitoo** [comment]
```
but incompatible with the architectures configured
```
安装的包跟你所在的架构不是同一个。自己编一个吧

**Comment by LMX58** [comment]
放弃了...搞不定
