### ISSUE TITLE
No clear license for this project

### ISSUE THREAD

**Issue by Icenowy** [zonyitoo/sysuh3c#28]
This project doesn't come with any COPYING or LICENSE file, and no file has copyright headers, except md5.cpp which is Public Domain code.

Could a license be applied to it?

**Comment by zonyitoo** [comment]
Sure. I would prefer MIT License.

 @benwwchen , will you license your contributions under MIT License?

**Comment by benwwchen** [comment]
@zonyitoo Yes, of course. 😅
