### ISSUE TITLE
OrangePi 执行 scons -Q 出错

### ISSUE THREAD

**Issue by Wuhj9608** [zonyitoo/sysuh3c#29]
我用 git clone https://github.com/zonyitoo/sysuh3c 下载后进入 sysuh3c/src 执行 scons -Q，出现以下报错:
```
root@OrangePI:~/temp/sysuh3c/src# scons -Q
o eapauth/eapauth.o -c -O2 -std=c++11 -I./eapauth -DWITH_SHOWMESSAGE -DSYSTEM_LINUX eapauth/eapauth.cpp
sh: 1: o: not found
o eapauth/eapdef.o -c -O2 -std=c++11 -I./eapauth -DWITH_SHOWMESSAGE -DSYSTEM_LINUX eapauth/eapdef.cpp
sh: 1: o: not found
o eapauth/eaputils.o -c -O2 -std=c++11 -I./eapauth -DWITH_SHOWMESSAGE -DSYSTEM_LINUX eapauth/eaputils.cpp
sh: 1: o: not found
o eapauth/md5.o -c -O2 -std=c++11 -I./eapauth -DWITH_SHOWMESSAGE -DSYSTEM_LINUX eapauth/md5.cpp
sh: 1: o: not found
ar rc eapauth/libeapauth.a eapauth/eapauth.o eapauth/eapdef.o eapauth/eaputils.o eapauth/md5.o
ar: eapauth/eapauth.o: No such file or directory
scons: *** [eapauth/libeapauth.a] Error 1
```
如果需要我提供其他关于硬件和软件的信息的话请说。

**Comment by zonyitoo** [comment]
`o`是什么东西？？？你设置了编译命令为`o`？

**Comment by Wuhj9608** [comment]
![screenshot from 2017-09-30 07-22-40](https://user-images.githubusercontent.com/24664458/31039447-548fb2ca-a5b0-11e7-9060-cf298b1dcd5a.png)

这是完整的流程。`o`我也不知道是啥...

**Comment by zonyitoo** [comment]
你的系统的编译器是哪个，路径是什么，通过环境变量设置一下。

```bash
echo $CC
echo $CXX
```

这两个变量现在是什么值

**Comment by Wuhj9608** [comment]
你是说输入`echo $CC`和`echo $CXX`可以查看它们的值吗？下图好像显示它们没有值。该怎么设置呢？
![screenshot from 2017-09-30 10-00-45](https://user-images.githubusercontent.com/24664458/31041401-679a5a3e-a5c7-11e7-9db4-4fe153bfc78d.png)

**Comment by zonyitoo** [comment]
```
CC="gcc" CXX="g++" scons -Q
```

**Comment by Wuhj9608** [comment]
![screenshot from 2017-09-30 12-24-50](https://user-images.githubusercontent.com/24664458/31042424-5e4dc9ee-a5da-11e7-94ed-ccd7ff6a3867.png)

直接执行 `CC="gcc" CXX="g++" scons -Q` 命令吗？结果如图。还是说要在其他地方设置这两个变量？

**Comment by zonyitoo** [comment]
…………你这个系统有毒吧…………不知道为什么了，编译命令是`o`。你编其它东西也会这样么？

**Comment by Wuhj9608** [comment]
不好意思，不熟悉 Linux ，我要怎么测试 “编其他东西” 会不会这样呢？随便写个`hello, world`的`.c`文件然后用什么命令执行吗？

**Comment by yangtuo250** [comment]
gcc命令google一下就好了啊，问题是scons也应该有跟make差不多的Makefile吧，看你用的是默认，应该就是你系统有问题而不是操作不当。

**Comment by Wuhj9608** [comment]
![screenshot from 2017-09-30 13-37-38](https://user-images.githubusercontent.com/24664458/31042894-918a02c8-a5e4-11e7-86e6-9c49e3037288.png)

![screenshot from 2017-09-30 13-37-49](https://user-images.githubusercontent.com/24664458/31042895-96074126-a5e4-11e7-8a32-54da7858b185.png)

我的 `hello, world` 应该没打错吧？这样应该是系统的问题喽？

**Comment by yangtuo250** [comment]
你这是什么发行版的linux？抱歉我也没见过

**Comment by Wuhj9608** [comment]
![screenshot from 2017-09-30 13-44-44](https://user-images.githubusercontent.com/24664458/31042937-8c07a700-a5e5-11e7-8f39-3f6894798db1.png)

orangepi 修改的 Raspbian server ，`/etc/apt/sources.list` 里面是 `deb http://archive.raspbian.org/raspbian/ jessie main contrib non-free
`

**Comment by Wuhj9608** [comment]
应该是我的系统的问题，不是`sysuh3c`的问题， 多谢楼上二位的指教了。

**Comment by Wuhj9608** [comment]
在网上查了以下，貌似是因为我系统是 `arm` 平台的原因？（但是树莓派好像也是`arm`呀，我之前用树莓派倒是可以编译运行`sysuh3c`）

**Comment by zonyitoo** [comment]
不是硬件的原因，是你的操作系统的配置原因

**Comment by Wuhj9608** [comment]
搞不定这个问题，后来我换了别人推荐的`armbian`系统，可以编译运行`sysuh3c`了。
