### ISSUE TITLE
Compile with OpenWRT-SDK報錯

### ISSUE THREAD

**Issue by RotoDhoulmagus** [zonyitoo/sysuh3c#3]
```
git clone git@github.com:zonyitoo/sysuh3c.git -b openwrt package/sysuh3c
```

運行這一步彈出
Permission Denied (publickey) 
fatal: Could not read from remote repository 
Please make sure you have the correct access rights
似乎不是沒有科學上網的問題

**Comment by zonyitoo** [comment]
這是因為你沒有上傳SSH Key，看[Github Help](https://help.github.com/categories/56/articles)
