### ISSUE TITLE
Some question about eap-md5

### ISSUE THREAD

**Issue by TXZdream** [zonyitoo/sysuh3c#34]
I am interested in the auth of h3c, but I am stuck in the md5 part. I have tried md5(hex(id + password + challange)), but the answer is not matched with the eap response I got from wireshark. Can you point out the question?

**Comment by zonyitoo** [comment]
Remove the `hex`.

**Comment by TXZdream** [comment]
The challenge sent by auth server is in hex mode, but the password is written with string, if I remove the hex, which format I should use? Is it means I should transfer all of them from hex to string? I have tried a lot of method, but I can not solve it. 

Thanks for your reply.

**Comment by zonyitoo** [comment]
> The challenge sent by auth server is in hex mode, but the password is written with string, if I remove the hex, which format I should use?

Just concatenate them together! You don't need any "format"!.

https://github.com/zonyitoo/sysuh3c/blob/cpp0x/src/eapauth/eapauth.cpp#L104-L106

**Comment by TXZdream** [comment]
Thank you.
