### ISSUE TITLE
#error SYSUH3C doesn't support your platform.

### ISSUE THREAD

**Issue by pt10160** [zonyitoo/sysuh3c#39]
#error SYSUH3C doesn't support your platform.
请问因为什么原因会触发这个错误？

![c985a3856fe07cfc5147117243ab956](https://github.com/zonyitoo/sysuh3c/assets/51996256/048605c0-ac2a-47cb-9a78-1d3544466670)

**Comment by zonyitoo** [comment]
https://github.com/zonyitoo/sysuh3c/blob/cpp0x/src/eapauth/eaputils.cpp#L158

It only supports Linux & macOS.
