### ISSUE TITLE
安装的时候显示下面的错误？何解啊？

### ISSUE THREAD

**Issue by pengshp** [zonyitoo/sysuh3c#5]
root@OpenWrt:/tmp# opkg install sysuh3c_0.2-1_ar71xx.ipk
Unknown package ‘sysuh3c’.
Collected errors:
- pkg_hash_fetch_best_installation_candidate: Packages for sysuh3c found, but incompatible with the architectures configured
- opkg_install_cmd: Cannot install package sysuh3c.

**Comment by zonyitoo** [comment]
你的芯片不是 ar71xx 的吧

**Comment by Testla** [comment]
我也遇到了相似的提示，不过芯片和ipk都是mips的。下了SDK尝试重新编译，在SDK根目录下make没有生成ipk，make package/sysuh3c提示up to date。

**Comment by Testla** [comment]
解决了。执行opkg print-architecture发现没有ramips只有一个ramips-24kec，google了一下编辑/etc/opkg.conf在末尾加上原来打印出来的与ramips就装上了。不过还是好奇怎么自行编译。

**Comment by zonyitoo** [comment]
各位不要再用那里面编译好的版本了，那个都是两三年前我自己编译出来用的。
