### ISSUE TITLE
如何解决dhcp不到ipv4地址的问题呢？

### ISSUE THREAD

**Issue by Old-Pussy** [zonyitoo/sysuh3c#6]
openwrt配置wan口为dhcp后也无法获得ipv4地址，自然也无法拨号成功，有时候倒是能获得ipv6的地址。

**Comment by zonyitoo** [comment]
我印象中，好像你没有认证成功之前的确是没有IP地址的吧。
离校已数年，不知道是否有策略调整，可与其它在校的师弟/妹们交流一下。

另外这个不是sysuh3c的问题，将Close。
